# Generated by Django 4.1.3 on 2022-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=20)),
                ('Lastname', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
